---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-ingress
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/portforwards
  verbs:
  - create
- apiGroups:
  - backend.ingress.frantj.cc
  resources:
  - basicauths
  - proxies
  - redirects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking/v1
  resources:
  - ingressclasses
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking/v1
  resources:
  - ingresses/finalizers
  - ingresses/status
  verbs:
  - update
